"""
Bundle Generator Service

Assembles probability-weighted betting combos from existing predictions.
Bundles are pre-generated by admin, never on-demand per user.
"""
import json
import random
import logging
import uuid
from datetime import datetime, timezone
from typing import List, Dict, Any, Optional
from sqlalchemy.orm import Session
from sqlalchemy import cast, Date
from datetime import date, timedelta

from app.models.models import Fixture, Prediction, League, Bundle

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Tier configuration
# ---------------------------------------------------------------------------

TIER_CONFIG = {
    "safe":   {"target_odds": 8.0,   "min_picks": 3, "max_picks": 5,  "price": 999.0,  "label": "Safe Slip"},
    "medium": {"target_odds": 35.0,  "min_picks": 5, "max_picks": 8,  "price": 1999.0, "label": "Medium Slip"},
    "high":   {"target_odds": 150.0, "min_picks": 8, "max_picks": 12, "price": 2999.0, "label": "High Roller"},
    "mega":   {"target_odds": 650.0, "min_picks": 10, "max_picks": 15, "price": 4999.0, "label": "Mega Slip"},
}

ALLOWED_MARKETS = {"1", "X", "2", "over25", "btts"}
MIN_CONFIDENCE = 0.60


# ---------------------------------------------------------------------------
# Core helpers
# ---------------------------------------------------------------------------

def prob_to_odds(prob: float) -> float:
    if prob <= 0:
        return 0.0
    return round(1 / prob, 2)


def pick_match(pool: List[Dict]) -> Dict:
    """
    Pick from top-10 highest-confidence entries with randomness,
    so bundles differ even when run back-to-back.
    """
    sorted_pool = sorted(pool, key=lambda x: x["probability"], reverse=True)
    top = sorted_pool[:10]
    return random.choice(top)


def _build_match_pool(db: Session, days_ahead: int = 3) -> List[Dict]:
    """
    Build a pool of high-quality match/market candidates from upcoming
    predictions already stored in the database.
    """
    today = date.today()
    window = [today + timedelta(days=i) for i in range(days_ahead + 1)]

    rows = (
        db.query(Fixture, League, Prediction)
        .join(League, Fixture.league_id == League.id)
        .join(Prediction, Prediction.fixture_id == Fixture.id)
        .filter(
            cast(Fixture.kickoff, Date).in_(window),
            Fixture.status == "scheduled",
        )
        .order_by(Fixture.kickoff)
        .all()
    )

    pool: List[Dict] = []
    for fixture, league, pred in rows:
        markets = [
            {"market": "1",      "label": "Home Win",  "probability": pred.home_win_pct / 100},
            {"market": "X",      "label": "Draw",      "probability": pred.draw_pct / 100},
            {"market": "2",      "label": "Away Win",  "probability": pred.away_win_pct / 100},
            {"market": "over25", "label": "Over 2.5",  "probability": pred.over25_pct / 100},
            {"market": "btts",   "label": "BTTS",      "probability": pred.btts_pct / 100},
        ]

        # Only keep the best pick from each fixture (avoids correlated picks)
        best = max(markets, key=lambda m: m["probability"])
        if best["probability"] < MIN_CONFIDENCE:
            # Try any market above threshold
            candidates = [m for m in markets if m["probability"] >= MIN_CONFIDENCE]
            if not candidates:
                continue
            best = max(candidates, key=lambda m: m["probability"])

        pool.append({
            "fixture_id": fixture.id,
            "home_team":  fixture.home_team_name,
            "away_team":  fixture.away_team_name,
            "league":     league.name,
            "kickoff":    fixture.kickoff.isoformat(),
            "market":     best["market"],
            "market_label": best["label"],
            "probability": best["probability"],
        })

    return pool


def generate_bundle(pool: List[Dict], target_odds: float, min_picks: int, max_picks: int) -> Dict:
    """
    Select picks from the pool, multiplying odds until we reach target_odds.
    Returns the assembled bundle dict (not persisted yet).
    """
    selected: List[Dict] = []
    total_odds = 1.0
    remaining = pool.copy()

    # Track used fixtures so we don't double-pick the same match
    used_fixture_ids = set()

    while total_odds < target_odds and remaining:
        # Filter out already-used fixtures
        available = [m for m in remaining if m["fixture_id"] not in used_fixture_ids]
        if not available:
            break

        pick = pick_match(available)
        odds = prob_to_odds(pick["probability"])
        if odds <= 1.0:
            remaining.remove(pick)
            continue

        selected.append({
            "fixture_id":   pick["fixture_id"],
            "home_team":    pick["home_team"],
            "away_team":    pick["away_team"],
            "league":       pick["league"],
            "kickoff":      pick["kickoff"],
            "market":       pick["market"],
            "market_label": pick["market_label"],
            "odds":         odds,
            "probability":  round(pick["probability"] * 100, 1),
        })

        used_fixture_ids.add(pick["fixture_id"])
        total_odds *= odds
        remaining.remove(pick)

        if len(selected) >= max_picks:
            break

    return {
        "total_odds": round(total_odds, 2),
        "picks": selected,
        "pick_count": len(selected),
    }


# ---------------------------------------------------------------------------
# Public API — called by admin endpoints
# ---------------------------------------------------------------------------

def generate_and_save_bundle(db: Session, tier: str) -> Optional[Bundle]:
    """
    Generate a bundle for the given tier and persist it to the database.
    Deactivates any previous bundle of the same tier.

    Returns the new Bundle object or None if there aren't enough matches.
    """
    if tier not in TIER_CONFIG:
        raise ValueError(f"Unknown tier: {tier}. Must be one of {list(TIER_CONFIG)}")

    config = TIER_CONFIG[tier]
    pool = _build_match_pool(db, days_ahead=3)

    if len(pool) < config["min_picks"]:
        logger.warning(
            f"Bundle generation for tier '{tier}' skipped: "
            f"only {len(pool)} qualifying matches (need {config['min_picks']})."
        )
        return None

    result = generate_bundle(
        pool,
        target_odds=config["target_odds"],
        min_picks=config["min_picks"],
        max_picks=config["max_picks"],
    )

    if result["pick_count"] < config["min_picks"]:
        logger.warning(
            f"Bundle generation for tier '{tier}' produced only "
            f"{result['pick_count']} picks (minimum {config['min_picks']})."
        )
        return None

    # Compute expiry = kickoff of the first match in the bundle
    kickoffs = [p["kickoff"] for p in result["picks"] if p.get("kickoff")]
    expires_at = None
    if kickoffs:
        earliest = min(kickoffs)
        try:
            expires_at = datetime.fromisoformat(earliest.replace("Z", "+00:00"))
        except Exception:
            expires_at = None

    # Deactivate previous bundles of same tier
    db.query(Bundle).filter(Bundle.tier == tier, Bundle.is_active == True).update(
        {"is_active": False}
    )

    label = config["label"]
    name = f"{label} — {result['total_odds']}x Odds"

    bundle = Bundle(
        id=str(uuid.uuid4()),
        name=name,
        total_odds=result["total_odds"],
        picks=json.dumps(result["picks"]),
        tier=tier,
        price=config["price"],
        currency="KES",
        is_active=True,
        expires_at=expires_at,
    )
    db.add(bundle)
    db.commit()
    db.refresh(bundle)

    logger.info(f"Bundle generated: [{tier}] {name} — {result['pick_count']} picks, {result['total_odds']}x")
    return bundle
